x-common-env: &common-env
  SERVER_SECRET: secret
  SECRET: secret
  STORAGE_CONFIG: minio|minio?accessKey=minioadmin&secretKey=minioadmin
  MONGO_URL: mongodb://mongodb:27017
  DB_URL: mongodb://mongodb:27017
  ACCOUNTS_URL: http://account:3000
  STATS_URL: http://stats:4900

services:
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - db:/data/db
    networks:
      - huly-net

  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    command: server /data --address ":9000" --console-address ":9001"
    volumes:
      - files:/data
    networks:
      - huly-net

  elastic:
    image: elasticsearch:7.14.2
    container_name: elastic
    restart: unless-stopped
    command: |
      /bin/sh -c "./bin/elasticsearch-plugin list | grep -q ingest-attachment || yes | ./bin/elasticsearch-plugin install --silent ingest-attachment;
      /usr/local/bin/docker-entrypoint.sh eswrapper"
    volumes:
      - elastic:/usr/share/elasticsearch/data
    environment:
      - ELASTICSEARCH_PORT_NUMBER=9200
      - BITNAMI_DEBUG=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8082
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    networks:
      - huly-net

  rekoni:
    image: hardcoreeng/rekoni-service:v0.6.502
    container_name: rekoni
    restart: unless-stopped
    environment:
      <<: *common-env
    deploy:
      resources:
        limits:
          memory: 500M
    networks:
      - huly-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rekoni.rule=Host(`team.insighter.digital`) && PathPrefix(`/rekoni`)"
      - "traefik.http.routers.rekoni.entrypoints=https"
      - "traefik.http.routers.rekoni.tls=true"
      - "traefik.http.routers.rekoni.tls.certresolver=letsencrypt"
      - "traefik.http.services.rekoni.loadbalancer.server.port=4004"
      - "traefik.http.routers.rekoni.middlewares=rekoni-strip"
      - "traefik.http.middlewares.rekoni-strip.stripprefix.prefixes=/rekoni"

  transactor:
    image: hardcoreeng/transactor:v0.6.502
    container_name: transactor
    restart: unless-stopped
    environment:
      <<: *common-env
      SERVER_PORT: 3333
      SERVER_CURSOR_MAXTIMEMS: 30000
      FRONT_URL: http://front:8080
      FULLTEXT_URL: http://fulltext:4700
      LAST_NAME_FIRST: true
    networks:
      - huly-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transactor.rule=Host(`team.insighter.digital`) && PathPrefix(`/transactor`)"
      - "traefik.http.routers.transactor.entrypoints=https"
      - "traefik.http.routers.transactor.tls=true"
      - "traefik.http.routers.transactor.tls.certresolver=letsencrypt"
      - "traefik.http.services.transactor.loadbalancer.server.port=3333"
      - "traefik.http.routers.transactor.middlewares=transactor-strip"
      - "traefik.http.middlewares.transactor-strip.stripprefix.prefixes=/transactor"

  collaborator:
    image: hardcoreeng/collaborator:v0.6.502
    container_name: collaborator
    restart: unless-stopped
    environment:
      <<: *common-env
      COLLABORATOR_PORT: 3078
    networks:
      - huly-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collaborator.rule=Host(`team.insighter.digital`) && PathPrefix(`/collaborator`)"
      - "traefik.http.routers.collaborator.entrypoints=https"
      - "traefik.http.routers.collaborator.tls=true"
      - "traefik.http.routers.collaborator.tls.certresolver=letsencrypt"
      - "traefik.http.services.collaborator.loadbalancer.server.port=3078"
      - "traefik.http.routers.collaborator.middlewares=collaborator-strip"
      - "traefik.http.middlewares.collaborator-strip.stripprefix.prefixes=/collaborator"

  account:
    image: hardcoreeng/account:v0.6.502
    container_name: account
    restart: unless-stopped
    environment:
      <<: *common-env
      SERVER_PORT: 3000
      TRANSACTOR_URL: ws://transactor:3333;wss://team.insighter.digital/transactor
      FRONT_URL: http://front:8080
      MODEL_ENABLED: "*"
      ACCOUNT_PORT: 3000
    networks:
      - huly-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.account.rule=Host(`team.insighter.digital`) && PathPrefix(`/accounts`)"
      - "traefik.http.routers.account.entrypoints=https"
      - "traefik.http.routers.account.tls=true"
      - "traefik.http.routers.account.tls.certresolver=letsencrypt"
      - "traefik.http.services.account.loadbalancer.server.port=3000"
      - "traefik.http.routers.account.middlewares=account-strip"
      - "traefik.http.middlewares.account-strip.stripprefix.prefixes=/accounts"

  workspace:
    image: hardcoreeng/workspace:v0.6.502
    container_name: workspace
    restart: unless-stopped
    environment:
      <<: *common-env
      TRANSACTOR_URL: ws://transactor:3333;wss://team.insighter.digital/transactor
      MODEL_ENABLED: "*"
    networks:
      - huly-net

  front:
    image: hardcoreeng/front:v0.6.502
    container_name: front
    restart: unless-stopped
    environment:
      <<: *common-env
      SERVER_PORT: 8080
      ACCOUNTS_URL: https://team.insighter.digital/accounts
      REKONI_URL: https://team.insighter.digital/rekoni
      STATS_URL: https://team.insighter.digital/stats
      UPLOAD_URL: /files
      ELASTIC_URL: http://elastic:9200
      COLLABORATOR_URL: wss://team.insighter.digital/collaborator
      TRANSACTOR_URL: wss://team.insighter.digital/transactor
      GMAIL_URL: http://localhost:8088
      CALENDAR_URL: http://localhost:8095
      TELEGRAM_URL: http://localhost:8086
      LOVE_ENDPOINT: http://localhost:8096
      SIGN_URL: http://localhost:9000
      TITLE: Huly Self Host
      DEFAULT_LANGUAGE: en
      LAST_NAME_FIRST: true
    networks:
      - huly-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`team.insighter.digital`)"
      - "traefik.http.routers.front.entrypoints=https"
      - "traefik.http.routers.front.tls=true"
      - "traefik.http.routers.front.tls.certresolver=letsencrypt"
      - "traefik.http.services.front.loadbalancer.server.port=8080"
    depends_on:
      - mongodb
      - minio
      - elastic
      - account
      - transactor
      - collaborator

  fulltext:
    image: hardcoreeng/fulltext:v0.6.502
    container_name: fulltext
    restart: unless-stopped
    environment:
      <<: *common-env
      FULLTEXT_DB_URL: http://elastic:9200
      ELASTIC_INDEX_NAME: huly_storage_index
      REKONI_URL: http://rekoni:4004
    networks:
      - huly-net

  stats:
    image: hardcoreeng/stats:v0.6.502
    container_name: stats
    restart: unless-stopped
    environment:
      <<: *common-env
      PORT: 4900
    networks:
      - huly-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stats.rule=Host(`team.insighter.digital`) && PathPrefix(`/stats`)"
      - "traefik.http.routers.stats.entrypoints=https"
      - "traefik.http.routers.stats.tls=true"
      - "traefik.http.routers.stats.tls.certresolver=letsencrypt"
      - "traefik.http.services.stats.loadbalancer.server.port=4900"
      - "traefik.http.routers.stats.middlewares=stats-strip"
      - "traefik.http.middlewares.stats-strip.stripprefix.prefixes=/stats"

networks:
  huly-net:
    driver: bridge

volumes:
  db:
  elastic:
  files: